FROM freqtradeorg/freqtrade:stable

# Install FreqAI + extra dependencies
USER root
RUN pip install --no-cache-dir \
    lightgbm==4.3.0 \
    pandas_ta==0.3.14b \
    pytz==2024.1 \
    requests==2.31.0 \
    scikit-learn==1.4.2 \
    xgboost==2.0.3

USER ftuser
